name: NationWar
version: 1.0
main: com.nationwar.NationWar
api-version: '1.21.10'
commands:
  gamestart:
    description: 게임 시작 (콘솔 전용)
  메뉴:
    description: 메뉴 열기
  tpa:
    description: TPA 요청
  팀:
    description: 팀 생성
  국가창고:
    description: 국가 창고 열기