name: NationWar
version: 1.0
main: com.nationwar.NationWar
api-version: 1.21 # 서버 버전에 맞춰 조정
commands:
  메뉴:
    description: 메인 메뉴를 엽니다.
  gamestart:
    description: 게임을 시작합니다.
  팀:
    description: 팀 관리 명령어입니다.
  tpa:
    description: 팀원에게 텔레포트 요청을 보냅니다.
  국가창고:
    description: 팀 공용 창고를 엽니다.
  gamecontinue:
    description: 코어 데이터를 불러와 게임을 재개합니다.