name: NationWar
version: 1.0.0
main: com.nationwar.NationWar
api-version: 1.21
author: Mintina_

commands:
  메뉴:
    description: 국가전쟁 메뉴 열기
  gamestart:
    description: 게임 시작
    permission: nationwar.admin
  gamecontinue:
    description: 코어 불러오기
    permission: nationwar.admin
  팀:
    description: 팀 관련 명령어
  tpa:
    description: 팀원 TPA
  국가창고:
    description: 국가 공용 창고

permissions:
  nationwar.admin:
    default: op
